-- FF Crespo - MySQL schema for Wiros shared hosting
-- Run once in phpMyAdmin or: mysql -u user -p database < schema.sql

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS Categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  icon VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Subcategories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_category INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  FOREIGN KEY (id_category) REFERENCES Categories(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_category INT NOT NULL,
  id_subcategory INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  caption TEXT NULL,
  image VARCHAR(512) NULL,
  materials TEXT NULL,
  measures TEXT NULL,
  quantity TEXT NULL,
  details TEXT NULL,
  caution TEXT NULL,
  colors TEXT NULL,
  delay TEXT NULL,
  tags TEXT NULL,
  new_product TINYINT(1) NOT NULL DEFAULT 0,
  FOREIGN KEY (id_category) REFERENCES Categories(id) ON DELETE RESTRICT,
  FOREIGN KEY (id_subcategory) REFERENCES Subcategories(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_product INT NOT NULL,
  src VARCHAR(512) NOT NULL,
  FOREIGN KEY (id_product) REFERENCES Products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AdminUsers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AdminSessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(64) NOT NULL UNIQUE,
  userId INT NOT NULL,
  expiresAt DATETIME NOT NULL,
  FOREIGN KEY (userId) REFERENCES AdminUsers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ProductChangeRequests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  productId INT NULL,
  payload LONGTEXT NOT NULL,
  submittedById INT NOT NULL,
  reviewedById INT NULL,
  reviewNote TEXT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewedAt DATETIME NULL,
  FOREIGN KEY (submittedById) REFERENCES AdminUsers(id),
  FOREIGN KEY (reviewedById) REFERENCES AdminUsers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
